#!/usr/bin/env python3
"""
Glossary Monitor
================
Scans all labs64.io-* repositories for documentation changes and uses an
LLM via OpenRouter to keep the glossary up to date.

File layout
-----------
GLOSSARY-MANUAL.md        — manually maintained terms (source of truth for curated entries)
scripts/.glossary-auto.md — AI-maintained terms (internal; updated by this script)
GLOSSARY.md               — generated output: manual + auto merged and sorted alphabetically

The LLM receives manual terms as read-only context so it never duplicates them.
On each run only the auto source is updated; GLOSSARY.md is always regenerated from both.

Token-efficiency strategy
--------------------------
scripts/.glossary-state.json tracks the last-processed commit SHA per repository.

  - Repos whose HEAD SHA matches the stored SHA are skipped entirely.
  - Changed repos use the GitHub compare API to fetch only modified doc files.
  - Repos seen for the first time receive a full fetch (one-off bootstrap cost).

The LLM is called only when at least one doc file has actually changed.
The state file is committed only after an LLM call.

Usage (local):
    export GH_TOKEN=<github-pat>
    export OPENROUTER_API_KEY=<key>
    python scripts/glossary_monitor.py
"""

from __future__ import annotations

import base64
import json
import os
import re
import sys
import time
from pathlib import Path
from typing import Optional

import requests
from openai import OpenAI

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

GITHUB_API = "https://api.github.com"
GITHUB_ORG = "Labs64"
REPO_NAME_RE = re.compile(r"^labs64\.io")

DOC_EXTENSIONS = {".md", ".yaml", ".yml"}
MAX_FILE_BYTES = 60_000
SKIP_DIRS = {".git", "node_modules", "target", "build", "dist", ".github"}

FIXED_REPOS = [
    "labs64.io-checkout",
    "labs64.io-auditflow",
    "labs64.io-payment-gateway",
    "labs64.io-docs",
]

SCRIPT_DIR    = Path(__file__).resolve().parent
MANUAL_PATH   = SCRIPT_DIR.parent / "GLOSSARY-MANUAL.md"
AUTO_PATH     = SCRIPT_DIR / ".glossary-auto.md"
GLOSSARY_PATH = SCRIPT_DIR.parent / "GLOSSARY.md"
STATE_PATH    = SCRIPT_DIR / ".glossary-state.json"

OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
# Fallback chain passed to OpenRouter's native multi-model routing.
# OpenRouter tries each model in order automatically; we only handle retries
# for transient failures (rate limits, upstream overload) at the call level.
OPENROUTER_MODELS = [
    "nvidia/nemotron-3-ultra-550b-a55b:free",
    "openai/gpt-oss-120b:free",
    "openai/gpt-oss-20b:free",
]
_RETRY_DELAYS = [1, 2, 4, 8]  # seconds between successive retries

MAX_PROMPT_CHARS = 180_000

# Output table header (3-column, used in GLOSSARY.md)
TABLE_HEADER = "| Term | Context | Definition |\n|------|---------|------------|"

# Internal auto-file header (4-column, includes Source for link building)
AUTO_TABLE_HEADER = "| Term | Context | Definition | Source |\n|------|---------|------------|--------|"

# Fallback doc paths per context module (format: repo/path or just repo for root).
# The default branch is resolved at runtime via the GitHub API — never hardcoded.
# Only confirmed-public repos are listed; add entries as more repos go public.
CONTEXT_DOC_PATHS: dict[str, str] = {
    "Checkout":        "labs64.io-docs/checkout/checkout-service-spec-en.md",
    "Payment Gateway": "labs64.io-docs/payment-gateway/readme.md",
    "AuditFlow":       "labs64.io-auditflow",
}

# Runtime cache: repo_name → default branch (populated lazily or via prefetch in main())
_branch_cache: dict[str, str] = {}

GLOSSARY_GENERATED_COMMENT = (
    "<!-- Generated by scripts/glossary_monitor.py — do not edit directly.\n"
    "     To add or change terms manually, edit GLOSSARY-MANUAL.md instead. -->"
)


# ---------------------------------------------------------------------------
# State helpers
# ---------------------------------------------------------------------------

def load_state() -> dict[str, str]:
    if STATE_PATH.exists():
        try:
            return json.loads(STATE_PATH.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            pass
    return {}


def save_state(state: dict[str, str]) -> None:
    STATE_PATH.write_text(
        json.dumps(state, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# Table helpers
# ---------------------------------------------------------------------------

def get_default_branch(repo: str, token: Optional[str] = None) -> str:
    """
    Return the default branch for a repo, queried from the GitHub API.

    Results are cached in _branch_cache for the process lifetime.
    Falls back to 'master' if the repo is inaccessible (private / not found).
    Public repos can be queried without a token (subject to the unauthenticated
    rate limit of 60 req/hr); pass a token in main() to use the authenticated limit.
    """
    if repo not in _branch_cache:
        headers: dict[str, str] = {"Accept": "application/vnd.github+json",
                                    "X-GitHub-Api-Version": "2022-11-28"}
        if token:
            headers["Authorization"] = f"Bearer {token}"
        resp = requests.get(
            f"{GITHUB_API}/repos/{GITHUB_ORG}/{repo}",
            headers=headers,
            timeout=30,
        )
        _branch_cache[repo] = (
            resp.json().get("default_branch", "master") if resp.ok else "master"
        )
    return _branch_cache[repo]


def source_to_url(path: str) -> str:
    """
    Convert a source path to a full GitHub URL.

    Accepted formats:
      - 'repo-name/path/to/file.md#anchor'  →  full blob URL with anchor
      - 'repo-name/path/to/file.md'         →  full blob URL
      - 'repo-name'                          →  repo root URL
      - '' or already an https:// URL       →  returned as-is (empty → empty)

    The default branch is looked up from _branch_cache (pre-populated in main(),
    or fetched on-demand for public repos via the unauthenticated GitHub API).
    """
    if not path or path.startswith("http"):
        return path
    slash = path.find("/")
    if slash == -1:
        return f"https://github.com/Labs64/{path}"
    repo = path[:slash]
    rest = path[slash + 1:]
    branch = get_default_branch(repo)   # cache hit after main() pre-populates
    return f"https://github.com/Labs64/{repo}/blob/{branch}/{rest}"


def build_linked_context(context_str: str, source_str: str = "") -> str:
    """
    Build a linked markdown context string.

    context_str: plain comma-separated module names, e.g. "Checkout, Payment Gateway"
    source_str:  comma-separated source paths matching each module in order.
                 Empty position falls back to CONTEXT_DOC_PATHS for that module.
    """
    contexts = [c.strip() for c in context_str.split(",")]
    sources  = [s.strip() for s in source_str.split(",")] if source_str.strip() else []

    result = []
    for i, ctx in enumerate(contexts):
        raw  = sources[i] if i < len(sources) else ""
        path = raw or CONTEXT_DOC_PATHS.get(ctx, "")
        url  = source_to_url(path) if path else ""
        result.append(f"[{ctx}]({url})" if url else ctx)
    return ", ".join(result)


def extract_rows(text: str) -> list[str]:
    """Return data rows from a markdown table, skipping header and separator lines."""
    rows = []
    for line in text.splitlines():
        s = line.strip()
        if not s.startswith("|"):
            continue
        inner = s.replace("|", "").strip()
        if not inner or set(inner) <= {"-", " "}:
            continue                          # separator row
        if inner.lower().startswith("term"):
            continue                          # header row
        rows.append(s)
    return rows


def row_sort_key(row: str) -> str:
    """Alphabetical sort key: term text, stripped of bold markers, lowercased."""
    cols = row.split("|")
    term = cols[1].strip().strip("*").strip() if len(cols) > 1 else row
    return re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", term).lower()


def _to_output_row(row: str, is_auto: bool) -> tuple[str, str]:
    """
    Parse a table row and return (sort_key, 3-column output row).

    Auto rows (4-column) carry a Source column used to build per-term links.
    Manual rows (3-column) fall back to CONTEXT_DOC_PATHS for linking.
    In both cases any pre-existing markdown links in Context are stripped
    first (backward compatibility) so re-linking always starts from plain names.
    """
    cols = row.split("|")
    # Columns: [empty, term, context, definition, (source), empty]
    if len(cols) < 5:
        return "", row
    term = cols[1].strip()
    ctx  = cols[2].strip()
    defn = cols[3].strip()
    # Source column present in 4-column (auto) rows; absent in 3-column (manual) rows
    src  = cols[4].strip() if (is_auto and len(cols) >= 6) else ""

    # Strip any existing markdown links from the context value so we can re-link cleanly
    ctx_plain = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", ctx)

    linked_ctx = build_linked_context(ctx_plain, src)
    sort_key   = re.sub(r"[\[\]()_*`]", "", term).lower().strip()
    return sort_key, f"| {term} | {linked_ctx} | {defn} |"


def merge_glossary(manual_text: str, auto_text: str) -> str:
    """
    Merge manual and auto table rows into one sorted 3-column table.
    When the same term appears in both, the manual entry wins.
    """
    auto_rows: dict[str, str] = {}
    for r in extract_rows(auto_text):
        k, v = _to_output_row(r, is_auto=True)
        if k:
            auto_rows[k] = v

    manual_rows: dict[str, str] = {}
    for r in extract_rows(manual_text):
        k, v = _to_output_row(r, is_auto=False)
        if k:
            manual_rows[k] = v

    merged = {**auto_rows, **manual_rows}   # manual overwrites auto on collision
    sorted_rows = sorted(merged.values(), key=row_sort_key)
    return TABLE_HEADER + "\n" + "\n".join(sorted_rows) + "\n"


def _reachable(url: str, token: Optional[str]) -> bool:
    """Return True if the resource behind *url* exists.

    GitHub blob URLs (https://github.com/Labs64/<repo>/blob/<branch>/<path>)
    are checked via the Contents API so private repos work with the token and
    anchors (#section) are stripped before the request (HTTP can't validate them).
    All other URLs fall back to a plain HEAD request.
    """
    base = url.split("#")[0]   # anchors can't be validated over HTTP
    gh = re.match(
        r"https://github\.com/Labs64/([^/]+)/blob/([^/]+)/(.+)", base
    )
    if gh:
        repo, branch, path = gh.groups()
        api_url = (
            f"{GITHUB_API}/repos/{GITHUB_ORG}/{repo}/contents/{path}"
            f"?ref={branch}"
        )
        headers: dict[str, str] = {
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        if token:
            headers["Authorization"] = f"Bearer {token}"
        try:
            resp = requests.get(api_url, headers=headers, timeout=15)
            return resp.status_code == 200
        except Exception:
            return False
    # Repo-root URLs and anything else: plain HEAD
    try:
        resp = requests.head(base, timeout=15, allow_redirects=True)
        return resp.status_code < 400
    except Exception:
        return False


def check_and_strip_links(table: str, token: Optional[str]) -> str:
    """Verify every [text](url) in *table* is reachable.

    Unreachable links are replaced with plain text so a bad LLM-generated path
    never lands in GLOSSARY.md.  Each failure is reported to stderr.
    Unique URLs are deduplicated before checking to minimise API calls.
    """
    urls = dict.fromkeys(re.findall(r"\[[^\]]+\]\(([^)]+)\)", table))
    bad: set[str] = set()
    for url in urls:
        if not _reachable(url, token):
            print(f"  WARNING: unreachable link stripped — {url}", file=sys.stderr)
            bad.add(url)

    if not bad:
        return table

    def _strip(m: re.Match) -> str:  # type: ignore[type-arg]
        return m.group(1) if m.group(2) in bad else m.group(0)

    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", _strip, table)


def write_glossary(manual_text: str, auto_text: str, token: Optional[str] = None) -> None:
    """Regenerate GLOSSARY.md from both sources."""
    table = merge_glossary(manual_text, auto_text)
    print("Checking link reachability…")
    table = check_and_strip_links(table, token)
    GLOSSARY_PATH.write_text(
        GLOSSARY_GENERATED_COMMENT + "\n\n# Glossary\n\n" + table,
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# GitHub helpers
# ---------------------------------------------------------------------------

def _gh_headers(token: str) -> dict[str, str]:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def discover_repos(token: str) -> list[str]:
    found: set[str] = set(FIXED_REPOS)
    url: Optional[str] = f"{GITHUB_API}/orgs/{GITHUB_ORG}/repos"
    params: dict = {"per_page": 100, "type": "all"}
    while url:
        resp = requests.get(url, headers=_gh_headers(token), params=params, timeout=30)
        if resp.status_code == 404:
            print(f"WARNING: org '{GITHUB_ORG}' not found or token lacks org read scope.",
                  file=sys.stderr)
            break
        resp.raise_for_status()
        for repo in resp.json():
            if REPO_NAME_RE.match(repo["name"]):
                found.add(repo["name"])
        url = resp.links.get("next", {}).get("url")
        params = {}
    return sorted(found)


def get_head_sha(token: str, repo: str) -> Optional[str]:
    branch = get_default_branch(repo, token)
    url = f"{GITHUB_API}/repos/{GITHUB_ORG}/{repo}/commits/{branch}"
    resp = requests.get(url, headers=_gh_headers(token), timeout=30)
    if resp.status_code in (404, 403):
        return None
    resp.raise_for_status()
    return resp.json()["sha"]


def get_changed_doc_paths(
    token: str, repo: str, base_sha: str, head_sha: str
) -> tuple[list[str], list[str]]:
    url = f"{GITHUB_API}/repos/{GITHUB_ORG}/{repo}/compare/{base_sha}...{head_sha}"
    resp = _gh_get(token, url)
    if resp is None:
        return [], []
    data = resp.json()

    if data.get("ahead_by", 0) > 300:
        return ["__FULL_FETCH__"], []

    changed, removed = [], []
    for f in data.get("files", []):
        filename: str = f["filename"]
        if Path(filename).suffix.lower() not in DOC_EXTENSIONS:
            continue
        if any(part in SKIP_DIRS for part in Path(filename).parts):
            continue
        (removed if f["status"] == "removed" else changed).append(filename)
    return changed, removed


def fetch_file(token: str, repo: str, file_path: str) -> Optional[str]:
    url = f"{GITHUB_API}/repos/{GITHUB_ORG}/{repo}/contents/{file_path}"
    resp = _gh_get(token, url)
    if resp is None:
        return None
    data = resp.json()
    if data.get("size", 0) > MAX_FILE_BYTES:
        return None
    return base64.b64decode(data.get("content", "")).decode("utf-8", errors="ignore")


def _gh_get(token: str, url: str, retries: int = 3, backoff: float = 2.0) -> Optional[requests.Response]:
    """
    GET a GitHub API URL with retry on transient 5xx errors.
    Returns None (and logs a warning) if all retries are exhausted.
    Immediately returns None for 403/404 (permanent non-retriable).
    """
    for attempt in range(1, retries + 1):
        resp = requests.get(url, headers=_gh_headers(token), timeout=30)
        if resp.status_code in (403, 404):
            return None
        if resp.status_code < 500:
            resp.raise_for_status()
            return resp
        # 5xx: transient server error — wait and retry
        if attempt < retries:
            print(
                f"  WARNING: {resp.status_code} for {url} "
                f"(attempt {attempt}/{retries}), retrying in {backoff:.0f}s…",
                file=sys.stderr,
            )
            time.sleep(backoff)
            backoff *= 2
        else:
            print(
                f"  WARNING: {resp.status_code} for {url} after {retries} attempts — skipping.",
                file=sys.stderr,
            )
    return None


def _fetch_tree(token: str, repo: str, path: str, out: dict[str, str]) -> None:
    url = f"{GITHUB_API}/repos/{GITHUB_ORG}/{repo}/contents/{path}"
    resp = _gh_get(token, url)
    if resp is None:
        return
    items = resp.json()
    if not isinstance(items, list):
        return
    for item in items:
        name = item["name"]
        if item["type"] == "dir":
            if name not in SKIP_DIRS:
                _fetch_tree(token, repo, item["path"], out)
        elif item["type"] == "file":
            if (Path(name).suffix.lower() in DOC_EXTENSIONS
                    and item.get("size", 0) <= MAX_FILE_BYTES):
                content = fetch_file(token, repo, item["path"])
                if content is not None:
                    out[f"{repo}/{item['path']}"] = content


def fetch_all_docs(token: str, repo: str) -> dict[str, str]:
    docs: dict[str, str] = {}
    _fetch_tree(token, repo, "", docs)
    return docs


# ---------------------------------------------------------------------------
# LLM analysis
# ---------------------------------------------------------------------------

def build_docs_block(docs: dict[str, str]) -> str:
    parts, total = [], 0
    for path, content in docs.items():
        block = f"=== {path} ===\n{content}\n"
        if total + len(block) > MAX_PROMPT_CHARS:
            parts.append(f"=== {path} === [omitted — character limit reached]\n")
            break
        parts.append(block)
        total += len(block)
    return "\n".join(parts)


SYSTEM_PROMPT = """\
You are a technical writer maintaining the AI-generated section of a project glossary \
for the Labs64.IO platform. A separate manually curated section exists — your job is to \
keep only the AI-generated section accurate and complete based on documentation changes.

Critical output rule: your entire response must be a single markdown table — nothing else. \
No preamble, no reasoning, no analysis, no summary, no code fences. \
Start your response with the header row (| Term | …) and end with the last data row.\
"""

USER_PROMPT_TMPL = """\
## Manually curated terms (context only — do not duplicate or modify)

These terms are already defined and will always appear in the final glossary.
Do NOT include any of them in your response, even if the changed files mention them.

{manual_section}

## Current AI-generated glossary entries

{auto_section}

## Documentation files changed since the last run

These are ONLY the files added or modified across all labs64.io-* repositories
since the glossary was last updated — not the full documentation corpus.

{changed_docs}
{removed_section}
---

Update the AI-generated entries where the changed files justify it:

1. **Add** terms from the changed files absent from both sections above.
2. **Improve** AI-generated definitions made clearer by the changed files.
3. **Expand** the Context column for AI-generated terms confirmed in additional modules.
4. **Remove** an AI-generated term only if every file mentioning it has been deleted
   (listed under "Removed files") and no other documentation uses it. When in doubt, keep it.

Constraints:
- Only include terms used in human-readable prose — not source-code symbols (field names,
  class names, method names, API path parameters).
  If a source-code identifier clearly represents a meaningful domain concept, promote it to
  the natural-language term instead of using the identifier as the glossary entry.
  Example: a class named `CorrelationIdFilter` should become "Correlation ID", not the class name.
- Skip trivial terms (common English words, generic framework names like Spring Boot or Vue).
- Return a 4-column markdown table: header row + data rows.
  Columns: **Term** | **Context** | **Definition** | **Source**
- Terms in bold, sorted alphabetically.
- Context: comma-separated module names in plain text (e.g. "Checkout, Payment Gateway").
  Do NOT add markdown links — the build script links them automatically.
- Source: for each context entry (same order), provide the relative path to the documentation
  file that most directly defines or describes the term, in the format
  "repo-name/path/to/file.md#section-anchor". Use the file paths from the === headers above.
  If a context module has no matching file in the provided docs, leave that position empty.
  Multiple sources are comma-separated (one per context entry).
- Definitions: concise prose — no bullet points, no inline code snippets.

Return ONLY the markdown table (header row + data rows). No commentary, no fences, no thinking.
Your response must start with | and every line must start with |.
If no changes are warranted, return the current AI-generated section unchanged.
"""


def _extract_table(content: str) -> Optional[str]:
    """Return pipe-only lines from *content*, or None if there are none.

    Reasoning models (e.g. Nemotron) emit chain-of-thought before the table.
    Filtering to lines that start with | strips that preamble safely.
    """
    lines = [l for l in content.splitlines() if l.startswith("|")]
    return ("\n".join(lines) + "\n") if lines else None


def call_llm(
    manual_text: str,
    auto_text: str,
    changed_docs: dict[str, str],
    removed_paths: list[str],
) -> str:
    """Call the LLM via OpenRouter and return the updated auto section table.

    Model failover is delegated to OpenRouter's native multi-model routing
    (extra_body models + route=fallback).  This function only retries on
    transient failures (rate limits, upstream overload) where waiting helps.
    """
    client = OpenAI(
        base_url=OPENROUTER_BASE_URL,
        api_key=os.environ["OPENROUTER_API_KEY"],
    )

    removed_section = ""
    if removed_paths:
        removed_section = (
            "\n## Removed files\n\n"
            + "\n".join(f"- {p}" for p in removed_paths)
            + "\n\n"
        )

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {
            "role": "user",
            "content": USER_PROMPT_TMPL.format(
                manual_section=manual_text.strip(),
                auto_section=auto_text.strip(),
                changed_docs=build_docs_block(changed_docs),
                removed_section=removed_section,
            ),
        },
    ]

    last_error: str = ""

    for attempt in range(len(_RETRY_DELAYS) + 1):
        response = client.chat.completions.create(
            model=OPENROUTER_MODELS[0],          # primary; fallbacks via extra_body
            max_tokens=8192,
            messages=messages,
            extra_headers={
                "HTTP-Referer": "https://github.com/Labs64/labs64.io-docs",
                "X-Title": "Labs64 Glossary Monitor",
            },
            extra_body={
                "models": OPENROUTER_MODELS,     # OpenRouter fallback chain
                "route": "fallback",
            },
        )

        # OpenRouter surfaces errors (rate limits, upstream failures, etc.)
        # as a null choices list rather than an HTTP error code.
        if not response.choices or response.choices[0].message.content is None:
            finish = (
                response.choices[0].finish_reason if response.choices else "no choices"
            )
            last_error = f"finish_reason={finish!r}  {response.model_dump_json()}"
            if attempt < len(_RETRY_DELAYS):
                delay = _RETRY_DELAYS[attempt]
                print(
                    f"  retry {attempt + 1}: {delay} s  (error: {last_error})",
                    file=sys.stderr,
                )
                time.sleep(delay)
                continue
            break

        table = _extract_table(response.choices[0].message.content)
        if table is None:
            last_error = (
                "response contained no markdown table rows:\n"
                + response.choices[0].message.content
            )
            if attempt < len(_RETRY_DELAYS):
                delay = _RETRY_DELAYS[attempt]
                print(
                    f"  retry {attempt + 1}: {delay} s  (error: no table rows in response)",
                    file=sys.stderr,
                )
                time.sleep(delay)
                continue
            break

        return table

    raise RuntimeError(f"All retries exhausted. Last error:\n{last_error}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if not token:
        print("ERROR: set GH_TOKEN or GITHUB_TOKEN.", file=sys.stderr)
        sys.exit(1)
    if not os.environ.get("OPENROUTER_API_KEY"):
        print("ERROR: set OPENROUTER_API_KEY.", file=sys.stderr)
        sys.exit(1)
    if not MANUAL_PATH.exists():
        print(f"ERROR: {MANUAL_PATH} not found.", file=sys.stderr)
        sys.exit(1)

    state = load_state()

    # 1. Discover repos
    print("Discovering labs64.io-* repositories…")
    repos = discover_repos(token)
    print(f"  Repos: {repos}")

    # 2. Pre-populate default-branch cache (authenticated → higher rate limit).
    #    source_to_url() reads from this cache, so all URL generation after this
    #    point uses the correct branch per repo without extra API calls.
    print("Fetching default branches…")
    for repo in repos:
        branch = get_default_branch(repo, token)
        print(f"  {repo}: {branch}")

    # 3. Determine what changed across repos
    all_changed: dict[str, str] = {}
    all_removed: list[str] = []
    new_state: dict[str, str] = dict(state)

    for repo in repos:
        print(f"  Checking {repo}…", end=" ", flush=True)
        head_sha = get_head_sha(token, repo)
        if head_sha is None:
            print("inaccessible — skipped")
            continue

        stored_sha = state.get(repo)
        if stored_sha == head_sha:
            print("no new commits — skipped")
            new_state[repo] = head_sha
            continue

        if stored_sha is None:
            print("new repo, fetching all docs…", end=" ", flush=True)
            docs = fetch_all_docs(token, repo)
            all_changed.update(docs)
            print(f"{len(docs)} file(s)")
        else:
            changed_paths, removed_paths = get_changed_doc_paths(
                token, repo, stored_sha, head_sha
            )
            if changed_paths == ["__FULL_FETCH__"]:
                print("large changeset, fetching all docs…", end=" ", flush=True)
                docs = fetch_all_docs(token, repo)
                all_changed.update(docs)
                print(f"{len(docs)} file(s)")
            else:
                fetched = 0
                for fp in changed_paths:
                    content = fetch_file(token, repo, fp)
                    if content is not None:
                        all_changed[f"{repo}/{fp}"] = content
                        fetched += 1
                all_removed.extend(f"{repo}/{p}" for p in removed_paths)
                print(
                    f"{fetched} changed file(s)"
                    + (f", {len(removed_paths)} removed" if removed_paths else "")
                )

        new_state[repo] = head_sha

    # 3. Skip LLM call if no doc files changed
    if not all_changed and not all_removed:
        print("No documentation changes detected — glossary is up to date.")
        sys.exit(0)

    print(
        f"\n{len(all_changed)} changed file(s), {len(all_removed)} removed — "
        f"calling OpenRouter (models: {', '.join(OPENROUTER_MODELS)})…"
    )

    # 4. Read sources
    manual_text = MANUAL_PATH.read_text(encoding="utf-8")

    # Extract only the table portion of the auto file so that:
    #   a) the LLM sees the table it must update (not the human-readable preamble), and
    #   b) the change comparison is table-vs-table (not table vs. preamble+table).
    # Bootstrap with a minimal 4-column header matching the expected LLM contract.
    if AUTO_PATH.exists():
        auto_file_text = AUTO_PATH.read_text(encoding="utf-8")
        current_auto_table = "\n".join(
            line for line in auto_file_text.splitlines()
            if line.startswith("|")
        ) + "\n"
        if not current_auto_table.strip():
            current_auto_table = AUTO_TABLE_HEADER + "\n"
    else:
        current_auto_table = AUTO_TABLE_HEADER + "\n"

    # 5. Call LLM — manual terms are context only; LLM returns updated 4-column auto table
    proposed_auto = call_llm(manual_text, current_auto_table, all_changed, all_removed)

    # 6. Write auto source and regenerate GLOSSARY.md when the auto section changed.
    #    Context links are built from the Source column inside merge_glossary();
    #    no post-processing of the LLM output is needed here.
    glossary_changed = proposed_auto.strip() != current_auto_table.strip()
    if glossary_changed:
        AUTO_PATH.write_text(
            "# Glossary — AI-Generated Entries\n\n"
            "Internal source file maintained by `scripts/glossary_monitor.py`. "
            "Do not edit manually.\n\n"
            + proposed_auto + "\n",
            encoding="utf-8",
        )
        write_glossary(manual_text, proposed_auto, token)
        print("GLOSSARY.md regenerated.")
    else:
        print("LLM found no glossary changes needed.")

    # 8. Always persist state after an LLM call
    save_state(new_state)
    print("State file updated.")

    # 9. Signal GitHub Actions
    gha_output = os.environ.get("GITHUB_OUTPUT")
    if gha_output:
        with open(gha_output, "a", encoding="utf-8") as fh:
            fh.write(f"glossary_changed={'true' if glossary_changed else 'false'}\n")
            fh.write("state_changed=true\n")


if __name__ == "__main__":
    main()
